name: "📚 Documentation"

on:
  push:
    branches: [ master ]
    paths:
      - "docs/**"
    tags: "*"

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Get source code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Cache project dependencies (pip)
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements/*.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install -U -r requirements/documentation.txt
        python -m pip install -e .

    - name: Build documentation
      run: sphinx-build -b html docs docs/_build/html
